version: '3.8'			
services:
    apigateway:
        build:
         context: .
	 dockerfile: Dockerfile
        restart: always
        ports:
            - 9000:9000
        volumes:
         -.demo:/home
	